### ISSUE TITLE
Improve Curse Matching: 'Molasses' should not count towards 'ass'.

### ISSUE THREAD

**Issue by JoeDailey** [motocru/curse-bot#3]
As the title suggests, there is some work to be done to more intuitively match curses.

**Comment by JoeDailey** [comment]
People are losing faith in the bot because it triggers without any obvious swears:

> Lolll crazy thing is I didnt even swear -@AbsolutAlex

A quick solution would be to require whitespace before and/or after a curse here:
https://github.com/motocru/curse-bot/blob/1d6b766307e0b29e83a82e3c7240811bd7685a0f/bot.js#L93

```
- words = message.match(new RegExp(`${curses.curses.join("|")}`,"g"));
+ words = message.match(new RegExp(`\s${curses.curses.join("|")}\s`,"g"));
```

**Comment by motocru** [comment]
curses are now identified with a required space before and after the word in question is found by the regex. A space was added to the beginning and ending of the message so that curses that were at the start and end of the message are not dis-regarded.
https://github.com/motocru/curse-bot/blob/492a44bf1daef366240303963ea5d2a96ab8567f/bot.js#L91-L94

Spaces had to be removed from identified words as the regex would capture both the spaces in front and after the word making them not be recognized as the same word in the DB. Closing
https://github.com/motocru/curse-bot/blob/492a44bf1daef366240303963ea5d2a96ab8567f/bot.js#L106
