### ISSUE TITLE
Code Quality: Big IFs... what Else?

### ISSUE THREAD

**Issue by JoeDailey** [motocru/curse-bot#9]
This happens once in your code. There is a big `if {} else if {}` starting here:
https://github.com/motocru/curse-bot/blob/6d870abee030ef900986f101712449f45ce3bea5/bot.js#L71

*40 lines* later there is an `else`. This is hard to read because I can't quickly tell if there will actually be an 'else'. I recommend separating the content of these paths into separate functions.

```
// Answering the question, 'what does the bot do for each message' is
// now very, very clear.
bot.on('message', function(user, userID, channelID, message, evt) {
  if (message.substring(0,1) == '?') {
    const args = message.substring(1).split(' ');
    const cmd = args[0].toUpperCase();
    handleUserCommand(cmd, args);
  } else if (userID !== bot.id) {
    parseUserMessage(userID, message);
  }
});
```

There's a couple queues to watch for while coding that suggest you break this apart.
 - *40* is far too long. Stick to 10 or less. This is a loose guideline so use your best judgement.
 - If you are adding header-style comments at the being of your `if` or `else` scopes, a function would do better. 

---

**Bonus note:** This code can be rewritten to be even simpler. Since the bot shouldn't command itself (*hello apocalypse*) you can return early anytime the message is from the bot.

```
bot.on('message', function(user, userID, channelID, message, evt) {
  if (userID !== bot.id) return;

  if (message.substring(0,1) == '?') {
    const args = message.substring(1).split(' ');
    const cmd = args[0].toUpperCase();
    handleUserCommand(cmd, args);
  } else {
    parseUserMessage(userID, message);
  }
});
```

**Comment by motocru** [comment]
changed the initial if / else statement to be more of a choice between 2 functions rather than the large expanse it was before
https://github.com/motocru/curse-bot/blob/d43880bea00480ead2b1059ef55d99a6a5ed7ea5/bot.js#L72-L82

All bot commands are now in a switch statement in a single function that go into other functions to get data for their respective commands
https://github.com/motocru/curse-bot/blob/d43880bea00480ead2b1059ef55d99a6a5ed7ea5/bot.js#L89-L114

ParseMessage function used to compose of a large single if statement with no else. it has now been changed to verify if a message contains swears which it will then move on to the next step or it will return if there are no curse words
https://github.com/motocru/curse-bot/blob/d43880bea00480ead2b1059ef55d99a6a5ed7ea5/bot.js#L120-L129

BONUS:
upon message, the first line in that function now returns if the command is coming from the bot
https://github.com/motocru/curse-bot/blob/d43880bea00480ead2b1059ef55d99a6a5ed7ea5/bot.js#L72

Closing this issue
